//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storepos.Entitites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Barang()
        {
            this.Laporanns = new HashSet<Laporann>();
        }
    
        public int IDBarang { get; set; }
        public string Nama_Barang { get; set; }
        public string Kode_Barang { get; set; }
        public Nullable<int> Jumlah_Stok { get; set; }
        public string Harga_Satuan { get; set; }
        public System.DateTime Tanggal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Laporann> Laporanns { get; set; }
    }
}
