//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storepos.Entitites
{
    using System;
    using System.Collections.Generic;
    
    public partial class BARANG___
    {
        public int ID { get; set; }
        public string IDBarang { get; set; }
        public string NamaBarang { get; set; }
        public string KodeBarang { get; set; }
        public int JumlahStock { get; set; }
        public decimal HargaBarang { get; set; }
        public System.DateTime Tanggal { get; set; }
    }
}
