//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storepos.Entitites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barang
    {
        public int IDBarang { get; set; }
        public string Nama_Barang { get; set; }
        public string Kode_Barang { get; set; }
        public Nullable<int> Jumlah_Stok { get; set; }
        public string Harga_Satuan { get; set; }
        public System.DateTime Tanggal { get; set; }
    }
}
