//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storepos.Entitites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Itemid { get; set; }
        public string ItemName { get; set; }
        public decimal ItemPrice { get; set; }
    }
}
